spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?characterEncoding=utf8&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: 123456
mapper:
  use-simple-type: true # 默认为TRUE,不映射简单类型。
  not-empty: true  #insertSelective和updateByPrimaryKeySelective中，是否判断字符串类型 !=''.
  style: camelhump #驼峰转下划线
  check-example-entity-class: true # 默认false,用于校验通用 Example 构造参数 entityClass 是否和当前调用的 Mapper<EntityClass> 类型一致。
  safe-delete: true
#  safe-update: true

